upd /project page
crowdforce/crowdforce-ui pull request #62
Opened 2022-09-02 16:42 UTC by manhir

2022-09-06 15:57 UTC, manhir commented on src/components/ProjectAside/index.tsx
> +            {React.cloneElement(asideTabComponents[openId], { data })}
might be better to just make those as mantine tabs

2022-09-08 14:30 UTC, tmshv requested changes

2022-09-08 14:30 UTC, tmshv commented on src/components/UserButton/WithIcon.tsx
> +export const UserButtonWithIcon: React.FC<UserButtonWithIconProps> = () => {
чем этот компонент отличается от того что в `index.tsx`?

2022-09-08 14:30 UTC, tmshv commented on src/components/SchemaMap/index.tsx
> +                    })}
вообще всю группу в отдельный компонент

2022-09-08 14:30 UTC, tmshv commented on src/components/SchemaMap/index.tsx
> +    const { schema: map } = useMap()
нужно использовать значение из `id` вместо `"schema"`

2022-09-08 14:30 UTC, tmshv commented on src/components/ProjectTasksList/index.tsx
> +const tasksDataPlaceholder = [
убрать в бекэнд

2022-09-08 14:30 UTC, tmshv commented on src/components/ProjectSideMenu/index.tsx
> +    return (
сам лейаут компонента надо вынести в отдельный компонент

2022-09-08 14:30 UTC, tmshv commented on src/components/ProjectAsideTab/Info.tsx
> +                                    Папочка Эльф
все это в бекэнд

2022-09-08 14:54 UTC, manhir commented on src/components/UserButton/WithIcon.tsx
> +export const UserButtonWithIcon: React.FC<UserButtonWithIconProps> = () => {
это был компонент для логин-кнопки которая выглядит не как стандартная, сережа на главной в самом верху нарисовал здоровую кнопку для логина

главная разница что этот компонент ссылается на другой html файл `https://crowdforce.ru/loginButtonWithIcon.html`

пока не добавлять этот компонент?

2022-09-08 21:19 UTC, tmshv requested changes

2022-09-08 21:19 UTC, tmshv commented on src/components/ProjectAside/index.tsx
> +    data: ProjectDto
нужно описать пропсы напрямую, без зависимостей из `common/types`

2022-09-08 21:19 UTC, tmshv commented on src/components/ProjectSideMenu/index.tsx
> +                .map((x, i) => wide ? (
`wide` — это что?

2022-09-09 11:25 UTC, manhir commented on src/components/ProjectSideMenu/index.tsx
> +                .map((x, i) => wide ? (
это широкое\узкое черное меню (`<ProjectSideMenu>`)
может стоит получше назвать `wide`

2022-09-09 13:02 UTC, manhir commented
может типы для фронта стоит вынести в `/types/XXX` а не в компонентах наваливать

2022-09-13 14:14 UTC, tmshv requested changes

2022-09-13 14:14 UTC, tmshv commented on pages/project/[projectId]/index.tsx
> +    const isInit = isAdmin && adminData?.status == "Init"
No admin requests on public page

2022-09-13 14:14 UTC, tmshv commented on pages/project/[projectId]/index.tsx
> +                    >
Replace `div` with `matine` components

2022-09-13 14:14 UTC, tmshv commented on pages/project/[projectId]/index.tsx
> +    const adminProject = await getAdminProject(projectId)
No admin requests on public page

2022-09-13 14:14 UTC, tmshv commented on src/components/App/index.tsx
> +                            width: " fit-content",
trailing space

2022-09-13 14:14 UTC, tmshv commented on src/components/ProjectAsideTab/Edit.tsx
> +    const { data, error } = useSWR(`/api/admin/projects/${dataPublic?.id}`)
rm this

2022-09-13 15:18 UTC, tmshv requested changes

2022-09-13 15:18 UTC, tmshv commented on src/components/ProjectSideMenu/ProjectSideMenuLayout.tsx
> +export const ProjectSideMenuLayout: React.FC<ProjectSideMenuLayoutProps> = ({ topButtons, bottomButtons }) => {
1. Component and file name `ProjectSideMenuLayout` -> `SideMenu`
2. Move to `src/components`
3. no context dependency
4. `topButtons` -> `children`
5. `bottomButtons` -> `extra?`

2022-09-13 15:18 UTC, tmshv commented on src/components/ProjectSideMenu/ProjectSideMenuLayout.tsx
> +export const ProjectSideMenuLayout: React.FC<ProjectSideMenuLayoutProps> = ({ topButtons, bottomButtons }) => {
fix linter warnings

2022-09-17 21:46 UTC, merged